The grass dwindles away to soil then rock and sand as it meets a river bank. Deep, fast moving and murky. It definitely looks too dangerous to swim across. Trees fill the opposite side of the bank.
END
RIVER
Its murky depths splash and foam as it rushes by.
TREES
Tall, thick evergreens populate the far bank of the river. They are so numerous that they block out the view through them.
END
END


