High up above the clouds you have arrived at the cloud kingdom. 

This represents the end of this test game and so a heartfelt well done to you. You can continue to go back down the beanstalk and explore to see if you missed anything but thankyou for sticking with it to get here.
END
CLOUDS
The clouds are light and fluffy. You can't fathom how you are able to stay on them without falling through.
END
END


