This is the top of the bridge from. We are high enough up that I can see further up the river but we're still below the height of the trees along the river bank. 
END
RIVER
Its way down below me. Still looks dangerous even from here.
TREES
The tops of the trees are still slightly above me.
WATERFALL
Looking down over the edge from up here, you can see the rocks amongst the spray.
END
END


