You enter what appears to be the castle barracks. There's bunks for soldiers to rest in and a weapons cabinet on the end wall. A soldier sleeps in one of the bunks.
END
CABINET
You try the doors on the cabinet but you need a key to unlock this.
BUNKS
Simple beds, a pillow, blankets
SOLDIER
He's snoring very loudly and seems to be not having the best of sleeps as he's twitching and occassionally mumbling. A bad dream perhaps?
END
END


