The path ends here, the tree line wraps around the end of the path and some small logs are dotted around. This appears to be some sort of rest area.
END
SEAT
The log seats look 'functional'
LOG
The seat log appears to be a seat, very basic but somewhere to plant your butt if you were tired.
LOGS
The logs are basic seats from what I can tell. Somewhere to park yourself after a long hike.
END
END


