The river ends in a rapid and violent waterfall. The foaming water leaping over the jagged rocks before hurtling over the edge into a spray deep below. On this side of the bridge, the slope looks like its less severe here and heads upwards to a clearing.
END
WATERFALL
The water is really moving here. the rocks look really jagged and sharp and the spray creates a rainbow as the sunlight passed through it.
SLOPE
Its not steep like the other side, I think I can get up that.
END
END


