The cobbled road continues south. there are various stone carvings placed along the edges of the road. A castle is visible in the distance.
END
CARVINGS
The carvings are spaced fairly evenly along the road, as if to make the area look prettier than just a regular road.
CARVING
There are several designs, this one looks like a lion.
CASTLE
Its quite a way away but looks quite impressive.
END
END


