You have climbed inside the well and taken a few steps down the ladder. The well seems to go quite a way down as I can't see the bottom. The ladder seems to run the entire depth of what you can see so far.
END
LADDER
Its rusty, old but seems sturdy. I don't think its going to come free from the brickwork and drop you to your death, hopefully.
WELL
Its a brick design, seems well made but quite old.
END
END


