Welcome to the test adventure created with my Amospro based engine.

Hopefully this works as expected and doesnt present too many bugs.
The idea of this adventure isnt any singular goal or mission but to test the
various aspects of the engine itself. 

Read the readme.txt included with this download for a better understanding
of whats possible so far.

I'd love to hear any feedback so please, let me know what you think.
END
END
END


